#ifndef DIJKSTAS_PATHFINDER_GLOBAL_H
#define DIJKSTAS_PATHFINDER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DIJKSTAS_PATHFINDER_LIBRARY)
#  define DIJKSTAS_PATHFINDERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DIJKSTAS_PATHFINDERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DIJKSTAS_PATHFINDER_GLOBAL_H
